security:
  oauth2:
    client:
      client-id: 534164240258083
      client-secret: a8b980eb487d19ba0f6c4b1969de3985
      access-token-uri: https://graph.facebook.com/oauth/access_token
      user-authorization-uri: https://www.facebook.com/dialog/oauth
      token-name: oauth_token
      authentication-scheme: query
      client-authentication-scheme: form
    resource:
      user-info-uri: https://graph.facebook.com/me
