facebook:
  client:
    client-id: FACEBOOK_CLIENT_ID
    client-secret: FACEBOOK_CLIENT_SECRET
    access-token-uri: https://graph.facebook.com/oauth/access_token
    user-authorization-uri: https://www.facebook.com/dialog/oauth
    token-name: oauth_token
    authentication-scheme: query
    client-authentication-scheme: form
  resource:
    user-info-uri: https://graph.facebook.com/me
